spring.application.name=qlcv

spring.datasource.url=jdbc:mysql://localhost:3306/qlcv?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456Aa

# LẦN ĐẦU: create (tạo lại bảng)
spring.jpa.hibernate.ddl-auto=create
# ỔN RỒI ĐỔI LẠI:
# spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
server.error.include-message=always